apiVersion: apps/v1
kind: Deployment
metadata:
  name: exposed-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exposed-nginx
  template:
    metadata:
      labels:
        app: exposed-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
